### ISSUE TITLE
Cannot find module 'uuid/v4'

### ISSUE THREAD

**Issue by vyktor112** [mozilla-iot/webthing-node#36]
Hello,
while running `$ node single-thing.js ` i get this error:

```
module.js:549
    throw err;
    ^

Error: Cannot find module 'uuid/v4'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/webthing/node_modules/webthing/example/single-thing.js:10:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```
OS:
Raspbian Version:June 2018
Release date:2018-06-27
Kernel version:4.14
npm version 1.4.21
node version 8.11.1

**Comment by mrstegeman** [comment]
If you're running the examples, you need to do the following:
```bash
cd <path>/webthing-node
npm install
NODE_PATH=. node example/single-thing.js
```

**Comment by vyktor112** [comment]
I've ran it and got this error:
```
sudo npm install
(node:13055) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:120:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.62-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/webthing-node
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/webthing-node/npm-debug.log
npm ERR! not ok code 0
```
anyway, i realized that `uuid/v4` is required only for `simple-thing.js,` not for ` webthing-node`.

**Comment by mrstegeman** [comment]
Not sure why `npm` is bombing out. Why are you running it as root?
