### ISSUE TITLE
Unhandled promise in WebThingServer constructor

### ISSUE THREAD

**Issue by jaller94** [mozilla-iot/webthing-node#38]
I am not yet sure how to make my local issues reproducible, but I want to highlight the issue of multiple uncaught Promises in this framework.

Most recently my server got silently killed by Node 10.9.0 when running `npm start` of my project [webthing-add](https://gitlab.com/webthings/webthing-add).

Link to the Promise:
https://github.com/mozilla-iot/webthing-node/blob/aed7d52ba8f80d7acf14216e1edd4484cefef265/lib/server.js#L624-L645

Logged error when adding `.catch(console.error)`:
```
{ Error: spawn netstat ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:231:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn netstat',
  path: 'netstat',
  spawnargs: [ '-r', '-n', '-A', 'inet' ],
  cmd: 'netstat -r -n -A inet' }
```

**Comment by jaller94** [comment]
While this does not make an unhandled promise less bad, here is the background:
Also, one of the dependencies seems to require the operating command `netstat` to be installed.
The tool has been deprecated and removed from some distros. That’s why the server is failing for me now, after my switch to openSuse.

https://wiki.linuxfoundation.org/networking/net-tools
