### ISSUE TITLE
this.router.ws is not a function when trying to run any Example

### ISSUE THREAD

**Issue by davidchieregato** [mozilla-iot/webthing-node#90]
Hello, when I try to run any of the example scripts I get the error as title, the result follows:
```
C:\Users\david\Downloads\iot3>node simplest-thing.js 8888
Usage:

C:\Program Files\nodejs\node.exe C:\Users\david\Downloads\iot3\simplest-thing.js [port]

Try:
curl -X PUT -H 'Content-Type: application/json' --data '{"on": true }' http://localhost:8888/properties/on

C:\Users\david\Downloads\iot3\node_modules\webthing\lib\server.js:747
      this.router.ws('/', (ws, req) => thingHandler.ws(ws, req));
                  ^

TypeError: this.router.ws is not a function
    at new WebThingServer (C:\Users\david\Downloads\iot3\node_modules\webthing\lib\server.js:747:19)
    at runServer (C:\Users\david\Downloads\iot3\simplest-thing.js:49:18)
    at Object.<anonymous> (C:\Users\david\Downloads\iot3\simplest-thing.js:56:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
```
What's wrong?

**Comment by mrstegeman** [comment]
Did you install `webthing` via `npm install` or did you `git clone` this repo?
